name: minions-sprint-master-workspace
project_scope: main
project_type: monorepo
description: Agent to organize and sort daily granular task priority
tier: idea
lane: minions
priority: medium
oss: true
stack: [typescript]
repo: "https://github.com/mxn2020/minions-sprint-master"
deploy_url: null
last_active: 2026-02-25
tags: [minion, toolbox, ai-agent, automation, minions, sprint, master]
notes: null
id: 5937896c-e966-446e-b573-16de6fc04d36
category: minion-toolbox
